version: "3"
services:

  db:
    image: postgres
    container_name: db-pos
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=kristina_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  spring-app:
   build: .
   container_name: springboot
   environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://db-pos:5432/kristina_db
    - SPRING_DATASOURCE_USERNAME=postgres
    - SPRING_DATASOURCE_PASSWORD=postgres
    - SPRING_JPA_HIBERNATE_DDL_AUTO=update
   ports:
    - 8080:8080
   depends_on:
    - db
##   network_mode: "host"

volumes:
  db:
